[package]
name = "aegis-vault"
description = "Library for parsing and dumping Aegis vaults"

homepage = "https://github.com/louib/aegis-vault-rs"
repository = "https://github.com/louib/aegis-vault-rs"
documentation = "https://docs.rs/aegis-vault"

license = "GPL-3.0-only"

version = "0.0.0-placeholder-version"
edition = "2021"

readme = "README.md"

include = [
  "src/",
  "README.md",
  "LICENSE",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10"
anyhow = "1.0"
data-encoding = "2.3"
hex = {version = "0.4.3", features = ["serde"]}
scrypt = {version = "0.11", default-features = false}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = {version = "1.0", features = ["v4"]}
rand = "0.8"
ring = "0.16"
zeroize = {version = "1", features = ["zeroize_derive"]}
